/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int quote = 4;
  /** RegularExpression Id. */
  int alphanumeric = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\\"\"",
    "<alphanumeric>",
    "\"ADD\"",
    "\"IMAGE \"",
    "\"WITH \"",
    "\"SOURCE \"",
    "\"HEADING\"",
    "\"PARAGRAPH\"",
    "\"LINK\"",
    "\"AND\"",
    "\"\\n\"",
    "\"WITH LINK\"",
    "\"WITH TEXT\"",
    "\"WITH COLOR\"",
    "\"WITH FONT\"",
  };

}
